// ==========================================================
// BANTUIN — translate-langs.js
// Daftar bahasa yang didukung (nama ditampilkan dalam Bahasa Indonesia),
// disamakan dengan daftar bahasa Google Translate.
// ==========================================================

const TR_LANGS = [
  { code:'af', name:'Afrikaans' },
  { code:'sq', name:'Albania' },
  { code:'am', name:'Amharik' },
  { code:'ar', name:'Arab' },
  { code:'hy', name:'Armenia' },
  { code:'as', name:'Assam' },
  { code:'ay', name:'Aymara' },
  { code:'az', name:'Azerbaijan' },
  { code:'bm', name:'Bambara' },
  { code:'eu', name:'Basque' },
  { code:'be', name:'Belarusia' },
  { code:'bn', name:'Bengali' },
  { code:'bho', name:'Bhojpuri' },
  { code:'bs', name:'Bosnia' },
  { code:'bg', name:'Bulgaria' },
  { code:'ca', name:'Catalan' },
  { code:'ceb', name:'Cebuano' },
  { code:'ny', name:'Chichewa' },
  { code:'zh-CN', name:'China (Sederhana)' },
  { code:'zh-TW', name:'China (Tradisional)' },
  { code:'co', name:'Corsica' },
  { code:'hr', name:'Kroasia' },
  { code:'cs', name:'Ceko' },
  { code:'da', name:'Denmark' },
  { code:'dv', name:'Divehi' },
  { code:'doi', name:'Dogri' },
  { code:'nl', name:'Belanda' },
  { code:'en', name:'Inggris' },
  { code:'eo', name:'Esperanto' },
  { code:'et', name:'Estonia' },
  { code:'ee', name:'Ewe' },
  { code:'tl', name:'Filipina' },
  { code:'fi', name:'Finlandia' },
  { code:'fr', name:'Prancis' },
  { code:'fy', name:'Frisia' },
  { code:'gl', name:'Galisia' },
  { code:'lg', name:'Ganda' },
  { code:'ka', name:'Georgia' },
  { code:'de', name:'Jerman' },
  { code:'gom', name:'Konkani (Goa)' },
  { code:'el', name:'Yunani' },
  { code:'gn', name:'Guarani' },
  { code:'gu', name:'Gujarati' },
  { code:'ht', name:'Haiti (Kreol)' },
  { code:'ha', name:'Hausa' },
  { code:'haw', name:'Hawaii' },
  { code:'iw', name:'Ibrani' },
  { code:'hi', name:'Hindi' },
  { code:'hmn', name:'Hmong' },
  { code:'hu', name:'Hungaria' },
  { code:'is', name:'Islandia' },
  { code:'ig', name:'Igbo' },
  { code:'ilo', name:'Iloko' },
  { code:'id', name:'Indonesia' },
  { code:'ga', name:'Irlandia' },
  { code:'it', name:'Italia' },
  { code:'ja', name:'Jepang' },
  { code:'jw', name:'Jawa' },
  { code:'kn', name:'Kannada' },
  { code:'kk', name:'Kazakh' },
  { code:'km', name:'Khmer' },
  { code:'rw', name:'Kinyarwanda' },
  { code:'ko', name:'Korea' },
  { code:'kri', name:'Krio' },
  { code:'ku', name:'Kurdi' },
  { code:'ckb', name:'Kurdi (Sorani)' },
  { code:'ky', name:'Kirgistan' },
  { code:'lo', name:'Laos' },
  { code:'la', name:'Latin' },
  { code:'lv', name:'Latvia' },
  { code:'ln', name:'Lingala' },
  { code:'lt', name:'Lituania' },
  { code:'lb', name:'Luksemburg' },
  { code:'mk', name:'Makedonia' },
  { code:'mai', name:'Maithili' },
  { code:'mg', name:'Malagasi' },
  { code:'ms', name:'Melayu' },
  { code:'ml', name:'Malayalam' },
  { code:'mt', name:'Malta' },
  { code:'mi', name:'Maori' },
  { code:'mr', name:'Marathi' },
  { code:'mni-Mtei', name:'Meiteilon (Manipuri)' },
  { code:'lus', name:'Mizo' },
  { code:'mn', name:'Mongolia' },
  { code:'my', name:'Myanmar (Burma)' },
  { code:'ne', name:'Nepal' },
  { code:'no', name:'Norwegia' },
  { code:'or', name:'Odia (Oriya)' },
  { code:'om', name:'Oromo' },
  { code:'ps', name:'Pashto' },
  { code:'fa', name:'Persia' },
  { code:'pl', name:'Polandia' },
  { code:'pt', name:'Portugis' },
  { code:'pa', name:'Punjabi' },
  { code:'qu', name:'Quechua' },
  { code:'ro', name:'Rumania' },
  { code:'ru', name:'Rusia' },
  { code:'sm', name:'Samoa' },
  { code:'sa', name:'Sanskerta' },
  { code:'gd', name:'Skotlandia (Gaelic)' },
  { code:'nso', name:'Sepedi' },
  { code:'sr', name:'Serbia' },
  { code:'st', name:'Sesotho' },
  { code:'sn', name:'Shona' },
  { code:'sd', name:'Sindhi' },
  { code:'si', name:'Sinhala' },
  { code:'sk', name:'Slovakia' },
  { code:'sl', name:'Slovenia' },
  { code:'so', name:'Somalia' },
  { code:'es', name:'Spanyol' },
  { code:'su', name:'Sunda' },
  { code:'sw', name:'Swahili' },
  { code:'sv', name:'Swedia' },
  { code:'tg', name:'Tajik' },
  { code:'ta', name:'Tamil' },
  { code:'tt', name:'Tatar' },
  { code:'te', name:'Telugu' },
  { code:'th', name:'Thailand' },
  { code:'ti', name:'Tigrinya' },
  { code:'ts', name:'Tsonga' },
  { code:'tr', name:'Turki' },
  { code:'tk', name:'Turkmen' },
  { code:'ak', name:'Twi' },
  { code:'uk', name:'Ukraina' },
  { code:'ur', name:'Urdu' },
  { code:'ug', name:'Uighur' },
  { code:'uz', name:'Uzbek' },
  { code:'vi', name:'Vietnam' },
  { code:'cy', name:'Wales' },
  { code:'xh', name:'Xhosa' },
  { code:'yi', name:'Yiddish' },
  { code:'yo', name:'Yoruba' },
  { code:'zu', name:'Zulu' }
];

const TR_AUTO = { code:'auto', name:'Deteksi Bahasa' };

function trLangName(code){
  if(code === 'auto') return TR_AUTO.name;
  const f = TR_LANGS.find(l => l.code === code);
  return f ? f.name : code;
}
